services:
  - type: web
    name: express-ai
    env: node
    repo: https://github.com/akinsayesokpah82-rgb/Express-AI
    branch: main
    plan: free
    buildCommand: ""
    startCommand: "node server.js"
    region: oregon
